Snippy/Snippy.App/Models/ViewModels/SnippetViewModel.cs
using System.Collections.Generic;
using Snippy.App.Model;

namespace Snippy.App.Models.ViewModels
{
    public class SnippetViewModel
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public virtual IEnumerable<LabelButtonViewModel> Labels { get; set; }
    }
}

Snippy/Snippy.App/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using Snippy.App.Data.UnitOfWork;
using Snippy.App.Models.ViewModels;

namespace Snippy.App.Controllers
{
    public class LanguageController : BaseController
    {
        public LanguageController(ISnippyData data) : base(data)
        {
        }

        public ActionResult Details(int id)
        {
            var language = this.Data.Languages
                .All()
                .Where(l => l.Id == id)
                .ProjectTo<LanguageViewModel>()
                .FirstOrDefault();
                
            return View(language);
        }

    }
}

Snippy/Snippy.App/Controllers/SnippetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Microsoft.AspNet.Identity;
using Snippy.App.Data.UnitOfWork;
using Snippy.App.Model;
using Snippy.App.Models.InputModels;
using Snippy.App.Models.ViewModels;

namespace Snippy.App.Controllers
{
    public class SnippetController : BaseController
    {
        public SnippetController(ISnippyData data) : base(data)
        {
        }

        public ActionResult All()
        {
            var snippets = this.Data.Snippets
                .All()
                .OrderByDescending(s => s.CreationDateTime)
                .ProjectTo<SnippetViewModel>(); 
            
            return View(snippets);
        }

        public ActionResult Details(int id)
        {
            var snippet = this.Data.Snippets
                .All()
                .Where(s => s.Id == id)
                .ProjectTo<SnippetDetailsViewModel>()
                .FirstOrDefault();

            var oldComments = snippet.Comments;
            var newComments = oldComments.OrderByDescending(c => c.CreationDateTime);
            snippet.Comments = newComments;

            return View(snippet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddComment(CommentInputModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                model.AuthorId = this.User.Identity.GetUserId();
                model.CreationDateTime = DateTime.Now;
                model.SnippetId = Int16.Parse(RouteData.Values["id"].ToString());
                var comment = Mapper.Map<Comment>(model);
                this.Data.Comments.Add(comment);
                this.Data.SaveChanges();

                var commentDb = this.Data.Comments
                    .All()
                    .Where(c => c.Id == comment.Id)
                    .ProjectTo<CommentShortViewModel>()
                    .FirstOrDefault();

                return this.PartialView("DisplayTemplates/CommentShortViewModel", commentDb);
            }

            return this.Json("Error");
        }

        [Authorize]
        public ActionResult MySnippets()
        {
            var userId = this.User.Identity.GetUserId();

            var snippets = this.Data.Snippets
                .All()
                .Where(s => s.AuthorId == userId)
                .OrderByDescending(s => s.CreationDateTime)
                .ProjectTo<SnippetViewModel>();

            return View(snippets);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            this.LoadLanguages();

            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SnippetInputModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                var labelsString = Regex.Replace(model.LabelsString, @"\s*", "");
                var labels = new HashSet<Label>();
                List<string> labelNames = labelsString.Split(';').ToList<string>();
                foreach (var labelName in labelNames)
                {
                    var label = this.Data.Labels.All().FirstOrDefault(l => l.Text.ToLower() == labelName.ToLower());
                    if (label != null)
                    {
                        labels.Add(label);
                    }
                    else
                    {
                        var newLabel = new Label()
                        {
                            Text = labelName
                        };

                        this.Data.Labels.Add(newLabel);
                        this.Data.SaveChanges();

                        labels.Add(newLabel);
                    }
                }

                model.Labels = labels;               

                var snippet = Mapper.Map<Snippet>(model);
                snippet.AuthorId = this.User.Identity.GetUserId();
                snippet.CreationDateTime = DateTime.Now;
                this.Data.Snippets.Add(snippet);
                this.Data.SaveChanges();

                return this.RedirectToAction("Details", new { id = snippet.Id });
            }

            this.LoadLanguages();

            return this.View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(int id)
        {
            var snippet = this.Data.Snippets
                .All()
                .Where(s => s.Id == id)
                .FirstOrDefault();          
            var snippetInputModel = Mapper.Map<SnippetInputModel>(snippet);

            snippetInputModel.LabelsString = string.Join(";", snippet.Labels.Select(l => l.Text).ToList());

            this.LoadLanguages();

            return View(snippetInputModel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SnippetInputModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                var labelsString = Regex.Replace(model.LabelsString, @"\s*", "");
                var labels = new HashSet<Label>();
                List<string> labelNames = labelsString.Split(';').ToList<string>();
                foreach (var labelName in labelNames)
                {
                    var label = this.Data.Labels.All().FirstOrDefault(l => l.Text.ToLower() == labelName.ToLower());
                    if (label != null)
                    {
                        labels.Add(label);
                    }
                    else
                    {
                        var newLabel = new Label()
                        {
                            Text = labelName
                        };

                        this.Data.Labels.Add(newLabel);
                        this.Data.SaveChanges();

                        labels.Add(newLabel);
                    }
                }

                model.Labels = labels;

                var snippet = Mapper.Map<Snippet>(model);
                snippet.AuthorId = this.User.Identity.GetUserId();

                var snippetFromDb = this.Data.Snippets.All().FirstOrDefault(s => s.Id == model.Id);
                snippetFromDb.Title = snippet.Title;
                snippetFromDb.Labels = snippet.Labels;
                snippetFromDb.Description = snippet.Description;
                snippetFromDb.Code = snippet.Code;
                snippetFromDb.Language = snippet.Language;

                this.Data.Snippets.Update(snippetFromDb);
                this.Data.SaveChanges();

                return this.RedirectToAction("Details", new { id = snippetFromDb.Id });
            }

            this.LoadLanguages();

            return this.View(model);
        }

        private void LoadLanguages()
        {
            var languages = this.Data
                .Languages.All()
                .OrderBy(l => l.Name)
                .Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                });

            ViewBag.Languages = languages;
        }

    }
}

Snippy/Snippy.App/Views/Snippet/All.cshtml
@model System.Linq.IQueryable<Snippy.App.Models.ViewModels.SnippetViewModel>

@{
    ViewBag.Title = "All Snippets";
}

<h2>@ViewBag.Title</h2>
@Html.DisplayFor(x => x)

Snippy/Snippy.App/Views/Snippet/Create.cshtml
@model Snippy.App.Models.InputModels.SnippetInputModel

@{
    ViewBag.Title = "Add new snippet";
}

<h2>Add new snippet</h2>
@Html.Partial("_SnippetFormPartial", Model)

Snippy/Snippy.App/Views/Snippet/Details.cshtml
@using Microsoft.AspNet.Identity
@model Snippy.App.Models.ViewModels.SnippetDetailsViewModel

@{
    ViewBag.Title = Model.Title;
}

<h2>
    @Html.ActionLink(Model.Language.Name, "Details", "Language", new {id = Model.Language.Id}, new {@class = "btn btn-success"})
    @ViewBag.Title
    @if (Context.User.Identity.GetUserId() == Model.Author.Id)
    {
        @Html.ActionLink("Edit", "Edit", "Snippet", new { id = Model.Id }, new { @class = "btn btn-warning" })
    }
</h2>
<p>
    <span class="glyphicon glyphicon-user" aria-hidden="true"></span> @Model.Author.UserName on @Model.CreationDateTime.ToString("dd.MM.yyyy hh:mm:ss")<br />
    Labels:
    <p class="btn-toolbar">@Html.DisplayFor(s => s.Labels)<br /></p>
    @Model.Description
</p>

<pre  class="prettyprint">@Model.Code</pre>

Comments:
<div id="comments" class="row">
    @if (Model.Comments.Any())
    {
        @Html.DisplayFor(s => s.Comments);
    }
    else
    {
        <br/>
        <span>No Comments are available</span>
    }
</div>

@if (Context.User.Identity.IsAuthenticated)
{
    <div class="row">
        <h3>Add Comment</h3>
        @using (Ajax.BeginForm("AddComment", "Snippet", new { id = Model.Id }, new AjaxOptions()
        {
            HttpMethod = "POST",
            InsertionMode = InsertionMode.InsertBefore,
            UpdateTargetId = "comments",
            OnSuccess = "onAddCommentSuccess"
        }))
        {
            @Html.AntiForgeryToken()
            <input type="text" name="Content" value="" id="Content" />
            <input type="submit" name="submit" value="Add comment" />
        }
    </div>
}

@section scripts {
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>
        function onAddCommentSuccess() {
            document.getElementById("Content").value = "";
        }
    </script>
}

Snippy/Snippy.App/Views/Snippet/Edit.cshtml
@model Snippy.App.Models.InputModels.SnippetInputModel

@{
    ViewBag.Title = "Edit Snippet";
}

<h2>Edit Snippet</h2>
@Html.Partial("_SnippetFormPartial", Model)

Snippy/Snippy.App/Views/Snippet/MySnippets.cshtml
@model System.Linq.IQueryable<Snippy.App.Models.ViewModels.SnippetViewModel>

@{
    ViewBag.Title = "My Snippets";
}

<h2>My Snippets</h2>
@if (Model.Any())
{
    @Html.DisplayFor(x => x)
}
else
{
    <span>You have no snippets. You can @Html.ActionLink("create", "Create", "Snippet", new { }, new { }) one now.</span>
}